# Generated by Django 5.1 on 2024-10-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='title',
        ),
        migrations.AddField(
            model_name='tareas',
            name='descripcion',
            field=models.CharField(default=False, max_length=200),
        ),
        migrations.AddField(
            model_name='tareas',
            name='titulo',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
